#*******************************************************************************
# Define libraries
#*******************************************************************************

# Matrix algebra
add_subdirectory(algebra)

# Matrix algebra
add_subdirectory(sort)

# Logging system
add_subdirectory(log)
